#!/usr/bin/env python3
import sys
import os
import pkcs11
from pkcs11 import KeyType, ObjectClass, Mechanism, MechanismFlag, Attribute
from pkcs11.util import ec
from federation import hsm

# open ssl attempt
test_hash = "73902d2a365fff2724e26d975148124268ec6a84991016683817ea2c973b199b"
test_hash_bytes = bytes.fromhex(test_hash)
node_id = 0

hsm = hsm.HsmPkcs11("{}{}".format(os.environ['KEY_LABEL'], node_id))
sig = hsm.sign(test_hash_bytes)
print(sig.hex())
